#+TITLE: Random Essays and Thoughts
#+SUBTITLE: Vaibhav Pujari
#+OPTIONS: num:nil author:nil toc:nil e:nil timestamp:nil date:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css"/>

From time to time, I found that I have ran into discussions with smart people about interesting topics vastly spread across all that is there to be seen and experienced. Sometimes, I stumble into my own thoughts going into depths of enquiry when I read something interesting or watch a movie. When this happens, its easy to go haywire about things and never reach a useful conclusion, and some fun might be missed if I let things go unexplored. I try to write as an informal attempt to capture the thought processess of the moment (like a photograph captures the visual experience of a moment). I'd be surprized (pleasently) if someone other than me spends any time to read them.

- [[file:posts/data-information-technology.org][Data, Information and Technology]] (Oct 23, 2020)
- [[file:posts/the-promise.html][The promise (poem)]] (Aug 21, 2020)
- [[file:posts/concrete-mind-in-a-plastic-world.html][Concrete mind in a plastic world]] (Jan 2, 2020)
- [[file:posts/art-computational-and-assisted-creativity.html][Art, Computational and Assisted Creativity]] (Jul 12, 2019)
- [[file:posts/45-minutes-that-matter.html][45 Minutes that matter]] (Jun 28, 2018
- [[file:posts/my-experience-with-god.html][My experience with God]] (Oct 19, 2014)
